# Form implementation generated from reading ui file 'Menu1.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 890)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1331, 831))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1329, 829))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Barra1 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.Barra1.setGeometry(QtCore.QRect(0, 0, 1321, 821))
        self.Barra1.setStyleSheet("QFrame { \n"
"        background-color:  #202020; \n"
"        border:  none; \n"
"}")
        self.Barra1.setTitle("")
        self.Barra1.setObjectName("Barra1")
        self.Menu1 = QtWidgets.QListWidget(parent=self.Barra1)
        self.Menu1.setGeometry(QtCore.QRect(10, 10, 121, 811))
        self.Menu1.setStyleSheet("QFrame { \n"
"        background-color:  #000000; \n"
"        border: 2px solid #FFFFFF;\n"
"        border-radius: 8px;\n"
"}")
        self.Menu1.setObjectName("Menu1")
        self.Store = QtWidgets.QPushButton(parent=self.Barra1)
        self.Store.setGeometry(QtCore.QRect(30, 220, 81, 31))
        self.Store.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.Store.setObjectName("Store")
        self.Biblioteca = QtWidgets.QPushButton(parent=self.Barra1)
        self.Biblioteca.setGeometry(QtCore.QRect(30, 260, 81, 31))
        self.Biblioteca.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.Biblioteca.setObjectName("Biblioteca")
        self.Menu2 = QtWidgets.QListWidget(parent=self.Barra1)
        self.Menu2.setGeometry(QtCore.QRect(130, 10, 1181, 171))
        self.Menu2.setStyleSheet("QFrame { \n"
"        background-color:  #000000; \n"
"        border: 2px solid #FFFFFF;\n"
"        border-radius: 8px;\n"
"}")
        self.Menu2.setObjectName("Menu2")
        self.HOME = QtWidgets.QPushButton(parent=self.Barra1)
        self.HOME.setGeometry(QtCore.QRect(30, 60, 81, 121))
        self.HOME.setAutoFillBackground(False)
        self.HOME.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #808080;\n"
"    color: black;\n"
"}")
        self.HOME.setText("")
        self.HOME.setObjectName("HOME")
        self.Logo = QtWidgets.QLabel(parent=self.Barra1)
        self.Logo.setGeometry(QtCore.QRect(40, 70, 61, 81))
        self.Logo.setAutoFillBackground(False)
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/Logo/WhatsApp Image 2026-10-01 at 15.10.22 (1).jpeg"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.Conta = QtWidgets.QPushButton(parent=self.Barra1)
        self.Conta.setGeometry(QtCore.QRect(1230, 40, 51, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Conta.setFont(font)
        self.Conta.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.Conta.setIconSize(QtCore.QSize(100, 100))
        self.Conta.setObjectName("Conta")
        self.Amigos = QtWidgets.QPushButton(parent=self.Barra1)
        self.Amigos.setGeometry(QtCore.QRect(1020, 120, 91, 31))
        self.Amigos.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.Amigos.setObjectName("Amigos")
        self.Carrinho = QtWidgets.QPushButton(parent=self.Barra1)
        self.Carrinho.setGeometry(QtCore.QRect(1120, 120, 91, 31))
        self.Carrinho.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.Carrinho.setObjectName("Carrinho")
        self.Pesquisar = QtWidgets.QPushButton(parent=self.Barra1)
        self.Pesquisar.setGeometry(QtCore.QRect(260, 120, 591, 31))
        self.Pesquisar.setStyleSheet("QPushButton {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"    border: 2px solid #00FF00;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.Pesquisar.setObjectName("Pesquisar")
        self.Menu3 = QtWidgets.QListWidget(parent=self.Barra1)
        self.Menu3.setGeometry(QtCore.QRect(130, 180, 1181, 641))
        self.Menu3.setStyleSheet("QFrame { \n"
"        background-color:  #000000; \n"
"        border: 2px solid #FFFFFF;\n"
"        border-radius: 8px;\n"
"}")
        self.Menu3.setObjectName("Menu3")
        self.SELgta6 = QtWidgets.QPushButton(parent=self.Barra1)
        self.SELgta6.setGeometry(QtCore.QRect(180, 230, 201, 321))
        self.SELgta6.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #808080;\n"
"    color: black;\n"
"}")
        self.SELgta6.setText("")
        self.SELgta6.setAutoDefault(False)
        self.SELgta6.setFlat(False)
        self.SELgta6.setObjectName("SELgta6")
        self.GTA6_2 = QtWidgets.QLabel(parent=self.Barra1)
        self.GTA6_2.setGeometry(QtCore.QRect(200, 250, 161, 221))
        self.GTA6_2.setText("")
        self.GTA6_2.setPixmap(QtGui.QPixmap(":/GTA6/images.jfif"))
        self.GTA6_2.setScaledContents(True)
        self.GTA6_2.setObjectName("GTA6_2")
        self.SELMspider = QtWidgets.QPushButton(parent=self.Barra1)
        self.SELMspider.setGeometry(QtCore.QRect(410, 230, 201, 321))
        self.SELMspider.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #808080;\n"
"    color: black;\n"
"}")
        self.SELMspider.setText("")
        self.SELMspider.setAutoDefault(False)
        self.SELMspider.setFlat(False)
        self.SELMspider.setObjectName("SELMspider")
        self.Mspider = QtWidgets.QLabel(parent=self.Barra1)
        self.Mspider.setGeometry(QtCore.QRect(430, 250, 161, 221))
        self.Mspider.setText("")
        self.Mspider.setPixmap(QtGui.QPixmap(":/Mspider/images (68).jpg"))
        self.Mspider.setScaledContents(True)
        self.Mspider.setObjectName("Mspider")
        self.SELMinecraft = QtWidgets.QPushButton(parent=self.Barra1)
        self.SELMinecraft.setGeometry(QtCore.QRect(640, 230, 201, 321))
        self.SELMinecraft.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #808080;\n"
"    color: black;\n"
"}")
        self.SELMinecraft.setText("")
        self.SELMinecraft.setAutoDefault(False)
        self.SELMinecraft.setFlat(False)
        self.SELMinecraft.setObjectName("SELMinecraft")
        self.Minecraft = QtWidgets.QLabel(parent=self.Barra1)
        self.Minecraft.setGeometry(QtCore.QRect(660, 250, 161, 221))
        self.Minecraft.setText("")
        self.Minecraft.setPixmap(QtGui.QPixmap(":/Minecraft/3cdc624293ae885a197906ba94b1475a.png"))
        self.Minecraft.setScaledContents(True)
        self.Minecraft.setObjectName("Minecraft")
        self.ComprarBT = QtWidgets.QPushButton(parent=self.Barra1)
        self.ComprarBT.setGeometry(QtCore.QRect(190, 480, 91, 31))
        self.ComprarBT.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: black;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"}")
        self.ComprarBT.setObjectName("ComprarBT")
        self.CarrinhoBT = QtWidgets.QPushButton(parent=self.Barra1)
        self.CarrinhoBT.setGeometry(QtCore.QRect(290, 480, 81, 31))
        self.CarrinhoBT.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.CarrinhoBT.setObjectName("CarrinhoBT")
        self.Preco = QtWidgets.QPushButton(parent=self.Barra1)
        self.Preco.setGeometry(QtCore.QRect(200, 520, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Preco.setFont(font)
        self.Preco.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: #00FF00;\n"
"    border: 2px solid #00FF00;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.Preco.setObjectName("Preco")
        self.ComprarBT_2 = QtWidgets.QPushButton(parent=self.Barra1)
        self.ComprarBT_2.setGeometry(QtCore.QRect(420, 480, 91, 31))
        self.ComprarBT_2.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: black;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"}")
        self.ComprarBT_2.setObjectName("ComprarBT_2")
        self.CarrinhoBT_2 = QtWidgets.QPushButton(parent=self.Barra1)
        self.CarrinhoBT_2.setGeometry(QtCore.QRect(520, 480, 81, 31))
        self.CarrinhoBT_2.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.CarrinhoBT_2.setObjectName("CarrinhoBT_2")
        self.ComprarBT_3 = QtWidgets.QPushButton(parent=self.Barra1)
        self.ComprarBT_3.setGeometry(QtCore.QRect(650, 480, 91, 31))
        self.ComprarBT_3.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: black;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"}")
        self.ComprarBT_3.setObjectName("ComprarBT_3")
        self.CarrinhoBT_3 = QtWidgets.QPushButton(parent=self.Barra1)
        self.CarrinhoBT_3.setGeometry(QtCore.QRect(750, 480, 81, 31))
        self.CarrinhoBT_3.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: white;\n"
"    border: 2px solid #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"}")
        self.CarrinhoBT_3.setObjectName("CarrinhoBT_3")
        self.Desconto = QtWidgets.QPushButton(parent=self.Barra1)
        self.Desconto.setGeometry(QtCore.QRect(190, 520, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Desconto.setFont(font)
        self.Desconto.setStyleSheet("QPushButton {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"    border: 2px solid #00FF00;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.Desconto.setObjectName("Desconto")
        self.Preco_2 = QtWidgets.QPushButton(parent=self.Barra1)
        self.Preco_2.setGeometry(QtCore.QRect(430, 520, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Preco_2.setFont(font)
        self.Preco_2.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: #00FF00;\n"
"    border: 2px solid #00FF00;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.Preco_2.setObjectName("Preco_2")
        self.Desconto_2 = QtWidgets.QPushButton(parent=self.Barra1)
        self.Desconto_2.setGeometry(QtCore.QRect(420, 520, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Desconto_2.setFont(font)
        self.Desconto_2.setStyleSheet("QPushButton {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"    border: 2px solid #00FF00;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.Desconto_2.setObjectName("Desconto_2")
        self.Preco_3 = QtWidgets.QPushButton(parent=self.Barra1)
        self.Preco_3.setGeometry(QtCore.QRect(660, 520, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Preco_3.setFont(font)
        self.Preco_3.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color: #00FF00;\n"
"    border: 2px solid #00FF00;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.Preco_3.setObjectName("Preco_3")
        self.Desconto_3 = QtWidgets.QPushButton(parent=self.Barra1)
        self.Desconto_3.setGeometry(QtCore.QRect(650, 520, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Desconto_3.setFont(font)
        self.Desconto_3.setStyleSheet("QPushButton {\n"
"    background-color: #00FF00;\n"
"    color: black;\n"
"    border: 2px solid #00FF00;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.Desconto_3.setObjectName("Desconto_3")
        self.Scroll1 = QtWidgets.QScrollBar(parent=self.scrollAreaWidgetContents)
        self.Scroll1.setGeometry(QtCore.QRect(1280, 190, 20, 601))
        self.Scroll1.setStyleSheet("QScrollBar:vertical {\n"
"    background: #FOFOFO;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00FF00;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.Scroll1.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.Scroll1.setObjectName("Scroll1")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Store.setText(_translate("MainWindow", "Store"))
        self.Biblioteca.setText(_translate("MainWindow", "Biblioteca"))
        self.Conta.setText(_translate("MainWindow", "👤 HI!"))
        self.Amigos.setText(_translate("MainWindow", "👥 Amigos"))
        self.Carrinho.setText(_translate("MainWindow", "🛒 Carrinho"))
        self.Pesquisar.setText(_translate("MainWindow", "🎮 Pesquisar"))
        self.ComprarBT.setText(_translate("MainWindow", "Comprar"))
        self.CarrinhoBT.setText(_translate("MainWindow", "Carrinho"))
        self.Preco.setText(_translate("MainWindow", "          R$449,00 →  R$ 314,30"))
        self.ComprarBT_2.setText(_translate("MainWindow", "Comprar"))
        self.CarrinhoBT_2.setText(_translate("MainWindow", "Carrinho"))
        self.ComprarBT_3.setText(_translate("MainWindow", "Comprar"))
        self.CarrinhoBT_3.setText(_translate("MainWindow", "Carrinho"))
        self.Desconto.setText(_translate("MainWindow", "-30%"))
        self.Preco_2.setText(_translate("MainWindow", "          R$ 249,90 →  R$ 87,40"))
        self.Desconto_2.setText(_translate("MainWindow", "-65%"))
        self.Preco_3.setText(_translate("MainWindow", "          R$ 99,00→  R$ R$ 59,40"))
        self.Desconto_3.setText(_translate("MainWindow", "-40%"))


